const games = [
  // Mobile casual
  { name: "Temple Run", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2011 },
  { name: "Candy Crush", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2012 },
  { name: "Hill Climb Racing", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2012 },
  { name: "Kahoot", platforms: { xbox:false, playstation:false, pc:true, switch:false, ios:true }, multiplayer:true, releaseYear:2013 },
  { name: "Gartic Phone", platforms: { xbox:false, playstation:false, pc:true, switch:false, ios:true }, multiplayer:true, releaseYear:2020 },
  { name: "Agar.io", platforms: { xbox:false, playstation:false, pc:true, switch:false, ios:true }, multiplayer:true, releaseYear:2015 },
  { name: "Geometry Dash", platforms: { xbox:false, playstation:false, pc:true, switch:false, ios:true }, multiplayer:false, releaseYear:2013 },
  { name: "Subway Surfers", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2012 },
  { name: "Clash of Clans", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:true, releaseYear:2012 },
  { name: "Roblox", platforms: { xbox:true, playstation:false, pc:true, switch:false, ios:true }, multiplayer:true, releaseYear:2006 },
  { name: "Candy Crush Soda", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2014 },
  { name: "Crossy Road", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2014 },
  { name: "Flappy Bird", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2013 },
  { name: "Fruit Ninja", platforms: { xbox:true, playstation:true, pc:true, switch:true, ios:true }, multiplayer:false, releaseYear:2010 },
  { name: "Angry Birds", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2009 },
  { name: "Jetpack Joyride", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2011 },
  { name: "Temple Run 2", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2013 },
  { name: "Super Mario Run", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2016 },
  { name: "Hill Climb Racing 2", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:true, releaseYear:2016 },
  { name: "Brain Out", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2019 },

  // Console / Steam / PC
  { name: "Minecraft", platforms: { xbox:true, playstation:true, pc:true, switch:true, ios:true }, multiplayer:true, releaseYear:2011 },
  { name: "Fortnite", platforms: { xbox:true, playstation:true, pc:true, switch:true, ios:true }, multiplayer:true, releaseYear:2017 },
  { name: "Call of Duty", platforms: { xbox:true, playstation:true, pc:true, switch:false, ios:false }, multiplayer:true, releaseYear:2003 },
  { name: "FIFA", platforms: { xbox:true, playstation:true, pc:true, switch:true, ios:true }, multiplayer:true, releaseYear:1993 },
  { name: "2K", platforms: { xbox:true, playstation:true, pc:true, switch:true, ios:true }, multiplayer:true, releaseYear:1999 },
  { name: "Among Us", platforms: { xbox:true, playstation:true, pc:true, switch:true, ios:true }, multiplayer:true, releaseYear:2018 },
  { name: "Stardew Valley", platforms: { xbox:true, playstation:true, pc:true, switch:true, ios:true }, multiplayer:true, releaseYear:2016 },
  { name: "Terraria", platforms: { xbox:true, playstation:true, pc:true, switch:true, ios:true }, multiplayer:true, releaseYear:2011 },
  { name: "Mario Kart", platforms: { xbox:false, playstation:false, pc:false, switch:true, ios:false }, multiplayer:true, releaseYear:1992 },
  { name: "Pokemon Go", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:true, releaseYear:2016 },
  { name: "PUBG", platforms: { xbox:true, playstation:true, pc:true, switch:true, ios:true }, multiplayer:true, releaseYear:2017 },
  { name: "Terraria Mobile", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:true, releaseYear:2011 },
  { name: "Brain Test", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2018 },
  { name: "GTA V", platforms: { xbox:true, playstation:true, pc:true, switch:false, ios:false }, multiplayer:true, releaseYear:2013 },
  { name: "Overwatch", platforms: { xbox:true, playstation:true, pc:true, switch:false, ios:false }, multiplayer:true, releaseYear:2016 },
  { name: "League of Legends", platforms: { xbox:false, playstation:false, pc:true, switch:false, ios:false }, multiplayer:true, releaseYear:2009 },
  { name: "Genshin Impact", platforms: { xbox:false, playstation:true, pc:true, switch:false, ios:true }, multiplayer:true, releaseYear:2020 },
  { name: "Rocket League", platforms: { xbox:true, playstation:true, pc:true, switch:true, ios:false }, multiplayer:true, releaseYear:2015 },
  { name: "Hades", platforms: { xbox:true, playstation:true, pc:true, switch:true, ios:false }, multiplayer:false, releaseYear:2020 },
  { name: "Hollow Knight", platforms: { xbox:true, playstation:true, pc:true, switch:true, ios:false }, multiplayer:false, releaseYear:2017 },
  { name: "Cyberpunk 2077", platforms: { xbox:true, playstation:true, pc:true, switch:false, ios:false }, multiplayer:false, releaseYear:2020 },
  { name: "Terraria PC", platforms: { xbox:false, playstation:false, pc:true, switch:false, ios:false }, multiplayer:true, releaseYear:2011 },
  { name: "CS:GO", platforms: { xbox:false, playstation:false, pc:true, switch:false, ios:false }, multiplayer:true, releaseYear:2012 },
  { name: "Valorant", platforms: { xbox:false, playstation:false, pc:true, switch:false, ios:false }, multiplayer:true, releaseYear:2020 },
  { name: "Team Fortress 2", platforms: { xbox:false, playstation:false, pc:true, switch:false, ios:false }, multiplayer:true, releaseYear:2007 },
  { name: "Skyrim", platforms: { xbox:true, playstation:true, pc:true, switch:true, ios:false }, multiplayer:false, releaseYear:2011 },
  { name: "Terraria Switch", platforms: { xbox:false, playstation:false, pc:false, switch:true, ios:false }, multiplayer:true, releaseYear:2017 },
  { name: "Fall Guys", platforms: { xbox:true, playstation:true, pc:true, switch:true, ios:false }, multiplayer:true, releaseYear:2020 },
  { name: "Animal Crossing", platforms: { xbox:false, playstation:false, pc:false, switch:true, ios:false }, multiplayer:true, releaseYear:2001 },
  { name: "Super Mario Odyssey", platforms: { xbox:false, playstation:false, pc:false, switch:true, ios:false }, multiplayer:false, releaseYear:2017 },
  { name: "Super Smash Bros", platforms: { xbox:false, playstation:false, pc:false, switch:true, ios:false }, multiplayer:true, releaseYear:1999 },
  { name: "Minecraft Dungeons", platforms: { xbox:true, playstation:true, pc:true, switch:true, ios:false }, multiplayer:true, releaseYear:2020 },
  { name: "The Sims", platforms: { xbox:true, playstation:true, pc:true, switch:false, ios:false }, multiplayer:false, releaseYear:2000 },
  { name: "Roblox Mobile", platforms: { xbox:false, playstation:false, pc:true, switch:false, ios:true }, multiplayer:true, releaseYear:2006 },
  { name: "Pokemon Sword", platforms: { xbox:false, playstation:false, pc:false, switch:true, ios:false }, multiplayer:true, releaseYear:2019 },
  { name: "Pokemon Shield", platforms: { xbox:false, playstation:false, pc:false, switch:true, ios:false }, multiplayer:true, releaseYear:2019 },
  { name: "Plants vs Zombies", platforms: { xbox:true, playstation:true, pc:true, switch:true, ios:true }, multiplayer:false, releaseYear:2009 },
  { name: "Angry Birds 2", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2015 },
  { name: "Jetpack Joyride Mobile", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2011 },
  { name: "Crossy Road Mobile", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2014 },
  { name: "Fruit Ninja Mobile", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2010 },
  { name: "Brain Test 2", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2020 },
  { name: "Coin Master", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:true, releaseYear:2010 },
  { name: "8 Ball Pool", platforms: { xbox:false, playstation:false, pc:true, switch:false, ios:true }, multiplayer:true, releaseYear:2010 },
  { name: "Words With Friends", platforms: { xbox:false, playstation:false, pc:true, switch:false, ios:true }, multiplayer:true, releaseYear:2009 },
  { name: "Brain Test", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2018 },
  { name: "Geometry Dash Mobile", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2013 },
  { name: "Subway Surfers Mobile", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:false, releaseYear:2012 },
  { name: "Clash Royale", platforms: { xbox:false, playstation:false, pc:false, switch:false, ios:true }, multiplayer:true, releaseYear:2016 }